<?php

use WP\Plugin\AIChatbot\Settings\Connection;
use WP\Plugin\AIChatbot\Settings\Models;

?>
<div class="wp-plugin-ai-chatbot page-model-engine">
    <form method="post" action="">
        <?php
        wp_nonce_field('wp-ai-chatbot-model-engine') ?>
        <input type="hidden" name="action" value="update">

        <table class="form-table" role="presentation">
            <tbody>
            <tr>
                <th scope="row">
                    <label for="model-engine">Model Engine</label>
                </th>
                <td>
                    <select
                        <?php
                        echo $this->activeEngine->isFromEnv() ? 'disabled="disabled"' : '' ?>
                            id="model-engine"
                            name="model-engine"
                    >
                        <?php
                        foreach ($this->engines as $id => $engine) : ?>
                            <option
                                <?php
                                echo (($this->activeEngine)() === $id) ? 'selected="selected"' : '' ?>
                                    value="<?php
                                    echo $id ?>"
                            >
                                <?php
                                echo $engine['description'] ?>
                            </option>
                        <?php
                        endforeach; ?>
                    </select>
                </td>
            </tr>
            <tr data-connection="<?php
            echo Connection::FIELD_HOST ?>">
                <th scope="row">
                    <label for="<?php
                    echo Connection::FIELD_HOST ?>">Host</label>
                </th>
                <td>
                    <input
                            type="text"
                            id="<?php
                            echo Connection::FIELD_HOST ?>"
                            name="<?php
                            echo Connection::FIELD_HOST ?>"
                            value="<?php
                            echo $this->connection->getHost(); ?>"
                    >
                </td>
            </tr>
            <tr data-models="<?php
            echo Models::FIELD_EMBEDDING_MODEL ?>">
                <th scope="row">
                    <label for="<?php
                    echo Models::FIELD_EMBEDDING_MODEL ?>">Embedding Model</label>
                </th>
                <td>
                    <input
                            type="text"
                            class="modelInput"
                            id="<?php
                            echo Models::FIELD_EMBEDDING_MODEL ?>"
                            name="<?php
                            echo Models::FIELD_EMBEDDING_MODEL ?>"
                            value="<?php
                            echo $this->models->getEmbeddingModel(); ?>"
                    >
                </td>
            </tr>
            <tr data-models="<?php
            echo Models::FIELD_GENERATION_MODEL ?>">
                <th scope="row">
                    <label for="<?php
                    echo Models::FIELD_GENERATION_MODEL ?>">Generation Model</label>
                </th>
                <td>
                    <input
                            type="text"
                            class="modelInput"
                            id="<?php
                            echo Models::FIELD_GENERATION_MODEL ?>"
                            name="<?php
                            echo Models::FIELD_GENERATION_MODEL ?>"
                            value="<?php
                            echo $this->models->getGenerationModel(); ?>"
                    >
                </td>
            </tr>
            <tr>
                <th scope="row">
                    <label for="chatbotEnabled">Enable Chatbot</label>
                </th>
                <td>
                    <input
                        type="checkbox"
                        id="chatbotEnabled"
                        name="chatbotEnabled"
                        <?php echo $this->chatbotEnabled ? 'checked' : '' ?>
                    >
                </td>
            </tr>
            <tr>
                <th scope="row">
                    <label for="chatbotDefaultAnswer">Chatbot Default Answer</label>
                </th>
                <td>
                    <input
                            type="text"
                            id="chatbotDefaultAnswer"
                            name="chatbotDefaultAnswer"
                            value="<?php echo $this->chatbotDefaultAnswer ?>"
                    >
                </td>
            </tr>
            </tbody>
        </table>

        <p class="submit">
            <input type="submit" name="submit" id="submit" class="button button-primary" value="Save settings">
            <input type="button" id="installModels" class="button" value="Install Models">
        </p>
    </form>

    <input type="text" name="test_chatbot" id="test_chatbot">
    <button name="test_chatbot_submit" id="test_chatbot_submit" class="button button-primary">Test Chatbot</button>

    <div>
        <span class="spinner" style="float: unset"></span>
        <p id="regenerate_log"></p>
    </div>
</div>
