<div class="wp-plugin-ai-chatbot page-vectorDB">
    <form method="post" action="">
        <?php

        use WP\Plugin\AIChatbot\OpenSearchAWSService;
        use WP\Plugin\AIChatbot\Settings\Connection;
        use WP\Plugin\AIChatbot\Settings\PostTypes;

        $this->availablePostTypes = get_post_types([
                'public'                => true,
                'exclude_from_search'   => false
            ],'objects');


        wp_nonce_field('wp-ai-chatbot-vectordb') ?>
        <input type="hidden" name="action" value="update">

        <table class="form-table" role="presentation">
            <tbody>
            <tr>
                <th scope="row">
                    <label for="model-engine">Vector DB</label>
                </th>
                <td>
                    <select
                        <?php
                        echo $this->activeEngine->isFromEnv() ? 'disabled="disabled"' : '' ?>
                            id="vectorDB"
                            name="vectorDB"
                    >
                        <?php
                        foreach ($this->engines as $id => $engine) : ?>
                            <option
                                <?php
                                echo (($this->activeEngine)() === $id) ? 'selected="selected"' : '' ?>
                                    value="<?php
                                    echo $id ?>"
                            >
                                <?php
                                echo $engine['description'] ?>
                            </option>
                        <?php
                        endforeach; ?>
                    </select>
                </td>
            </tr>
            <tr data-connection="<?php echo Connection::FIELD_HOSTS ?>">
                <th scope="row">
                    <label for="<?php echo Connection::FIELD_HOSTS ?>">Hosts</label>
                </th>
                <td>
                        <textarea
                                rows="3"
                                id="<?php echo Connection::FIELD_HOSTS ?>"
                                name="<?php echo Connection::FIELD_HOSTS ?>"
                            <?php echo $this->connection->isFromEnv(Connection::FIELD_HOSTS) ? 'readonly="readonly"' : '' ?>
                        ><?php echo implode("\n", $this->connection->getHosts()); ?></textarea>
                </td>
            </tr>

            <tr data-connection="<?php echo Connection::FIELD_USER ?>">
                <th scope="row">
                    <label for="<?php echo Connection::FIELD_USER ?>">Username</label>
                </th>
                <td>
                    <input
                        <?php echo $this->connection->isFromEnv(Connection::FIELD_USER) ? 'readonly="readonly"' : '' ?>
                            id="<?php echo Connection::FIELD_USER ?>"
                            type="text"
                            name="<?php echo Connection::FIELD_USER ?>"
                            value="<?php echo htmlentities($this->connection->getUser()) ?>"
                    >
                </td>
            </tr>

            <tr data-connection="<?php echo Connection::FIELD_PASS ?>">
                <th scope="row">
                    <label for="<?php echo Connection::FIELD_PASS ?>">Password</label>
                </th>
                <td>
                    <input
                        <?php echo $this->connection->isFromEnv(Connection::FIELD_PASS) ? 'readonly="readonly"' : '' ?>
                            id="<?php echo Connection::FIELD_PASS ?>"
                            type="password"
                            name="<?php echo Connection::FIELD_PASS ?>"
                            value="<?php echo htmlentities($this->connection->getPass()) ?>"
                    >
                </td>
            </tr>

            <tr data-connection="<?php echo Connection::FIELD_INDEX ?>">
                <th scope="row">
                    <label for="<?php echo Connection::FIELD_INDEX ?>">Index</label>
                </th>
                <td>
                    <input
                        <?php echo $this->connection->isFromEnv(Connection::FIELD_INDEX) ? 'readonly="readonly"' : '' ?>
                            id="<?php echo Connection::FIELD_INDEX ?>"
                            type="text"
                            name="<?php echo Connection::FIELD_INDEX ?>"
                            value="<?php echo htmlentities($this->connection->getIndex()) ?>"
                    >
                </td>
            </tr>

            <tr data-post_types="<?php echo PostTypes::FIELD_POST_TYPES ?>">
                <th scope="row">
                    <label>Post Types</label>
                </th>
                <td>
                    <?php foreach ($this->availablePostTypes as $postType) :?>
                    <input
                           data-post_types-input="<?php echo $postType->name?>"
                           type="checkbox"
                           id="<?php echo PostTypes::FIELD_POST_TYPES . '[' . $postType->name . ']' ?>"
                           name="<?php echo PostTypes::FIELD_POST_TYPES . '[' . $postType->name . ']' ?>"
                           value="1"
                           <?php if (array_key_exists($postType->name, $this->postTypes->getPostTypes())) {
                                echo 'checked="checked"';
                           }?>
                    >
                        <label for="<?php echo PostTypes::FIELD_POST_TYPES . '[' . $postType->name . ']' ?>"><?php echo $postType->label?></label>
                        <br>
                    <?php endforeach; ?>
                </td>
            </tr>

            <tr data-connection="<?php echo Connection::FIELD_DISABLE_SSL_VERIFY ?>">
                <th scope="row">
                    <label for="<?php echo Connection::FIELD_DISABLE_SSL_VERIFY ?>">Disable SSL Verify</label>
                </th>
                <td>
                    <fieldset>
                        <label for="<?php echo Connection::FIELD_DISABLE_SSL_VERIFY ?>">
                            <input
                                    id="<?php echo Connection::FIELD_DISABLE_SSL_VERIFY ?>"
                                    type="checkbox"
                                    name="<?php echo Connection::FIELD_DISABLE_SSL_VERIFY ?>"
                                    value="1"
                                <?php echo $this->connection->getDisableSslVerify() ? 'checked="checked"' : '' ?>
                                <?php echo $this->connection->isFromEnv(Connection::FIELD_DISABLE_SSL_VERIFY) ? 'disabled="disabled"' : '' ?>
                            >
                        </label>
                    </fieldset>
                </td>
            </tr>

            <tr data-connection="<?php echo Connection::FIELD_OS_AWS_REGION ?>">
                <th scope="row">
                    <label for="<?php echo Connection::FIELD_OS_AWS_REGION ?>">AWS Region</label>
                </th>
                <td>
                    <input
                        <?php echo $this->connection->isFromEnv(Connection::FIELD_OS_AWS_REGION) ? 'readonly="readonly"' : '' ?>
                            id="<?php echo Connection::FIELD_OS_AWS_REGION ?>"
                            type="text"
                            name="<?php echo Connection::FIELD_OS_AWS_REGION ?>"
                            value="<?php echo htmlentities($this->connection->getOpenSearchAWSRegion()) ?>"
                    >
                </td>
            </tr>

            <tr data-connection="<?php echo Connection::FIELD_OS_AWS_SERVICE ?>">
                <th scope="row">
                    <label for="<?php echo Connection::FIELD_OS_AWS_SERVICE ?>">AWS Service</label>
                </th>
                <td>
                    <select
                        <?php echo $this->connection->isFromEnv(Connection::FIELD_OS_AWS_SERVICE) ? 'disabled="disabled"' : '' ?>
                            id="<?php echo Connection::FIELD_OS_AWS_SERVICE ?>"
                            name="<?php echo Connection::FIELD_OS_AWS_SERVICE ?>"
                    >
                        <option
                                value="<?php echo OpenSearchAWSService::OPENSEARCH->value ?>"
                            <?php echo ($this->connection->getOpenSearchAWSService() == OpenSearchAWSService::OPENSEARCH) ? 'selected="selected"' : '' ?>
                        >
                            Amazon OpenSearch Service
                        </option>
                        <option
                                value="<?php echo OpenSearchAWSService::OPENSEARCH_SERVERLESS->value ?>"
                            <?php echo ($this->connection->getOpenSearchAWSService() == OpenSearchAWSService::OPENSEARCH_SERVERLESS) ? 'selected="selected"' : '' ?>
                        >
                            Amazon OpenSearch Serverless
                        </option>
                    </select>
                </td>
            </tr>

            <tr data-connection="<?php echo Connection::FIELD_OS_AWS_KEY ?>">
                <th scope="row">
                    <label for="<?php echo Connection::FIELD_OS_AWS_KEY ?>">AWS Authentification Key</label>
                </th>
                <td>
                    <input
                        <?php echo $this->connection->isFromEnv(Connection::FIELD_OS_AWS_KEY) ? 'readonly="readonly"' : '' ?>
                            id="<?php echo Connection::FIELD_OS_AWS_KEY ?>"
                            type="text"
                            name="<?php echo Connection::FIELD_OS_AWS_KEY ?>"
                            value="<?php echo htmlentities($this->connection->getOpenSearchAWSKey()) ?>"
                    >
                </td>
            </tr>

            <tr data-connection="<?php echo Connection::FIELD_OS_AWS_SECRET ?>">
                <th scope="row">
                    <label for="<?php echo Connection::FIELD_OS_AWS_SECRET ?>">AWS Authentification Secret</label>
                </th>
                <td>
                    <input
                        <?php echo $this->connection->isFromEnv(Connection::FIELD_OS_AWS_SECRET) ? 'readonly="readonly"' : '' ?>
                            id="<?php echo Connection::FIELD_OS_AWS_SECRET ?>"
                            type="password"
                            name="<?php echo Connection::FIELD_OS_AWS_SECRET ?>"
                            value="<?php echo htmlentities($this->connection->getOpenSearchAWSSecret()) ?>"
                    >
                </td>
            </tr>
            <tr>
                <th scope="row">
                    <label for="searchTolerance">Search Tolerance</label>
                </th>
                <td>
                    <input type="number" step=0.00000001 min="0" max="1" id="searchTolerance" name="searchTolerance" value="<?php echo $this->searchTolerance ?>">
                </td>
            </tr>
            </tbody>
        </table>

        <p class="submit">
            <input type="submit" name="submit" id="submit" class="button button-primary" value="Save settings">
        </p>

    </form>
    <p>
        <input type="button" name="regenerate" id="regenerate" class="button button-primary" value="Neu generieren">

        <span class="spinner"></span>
    </p>

    <div id="regenerate_log">

    </div>
</div>
